org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true

mod_id=reliquary
mod_group_id=net.p3pp3rf1y
mod_version=2.0.61
sonar_project_key=xreliquary:Reliquary
github_package_url=https://maven.pkg.github.com/P3pp3rF1y/Reliquary

#neoforge
minecraft_version=1.20.1
minecraft_version_range=[1.20,1.21)
neo_version=47.1.5
neo_version_range=[47.1,)
loader_version_range=[47,)

#publish
curseforge_id=241319
release_type=release
release_versions=1.20.1
modrinth_project_id=fQO83PId

#deps
jei_mc_version=1.20.1-forge
jei_version=15.20.0.106
curios_version=5.7.0+1.20.1
botania_version=1.20.1-450-FORGE
patchouli_version=1.20.1-84.1-FORGE
jade_cf_file_id=4614153
# hwyla_version = 1.8.20-B35_1.12
# jer_version = 0.8.7.41
parchment_version=2023.09.03-1.20.1
